// src/lib/routing.js
// OpenRouteService — free tier: 2000 req/day
// Profile mapping per trip type

const ORS_BASE = 'https://api.openrouteservice.org/v2'

const ORS_PROFILE = {
  car:    'driving-car',
  moto:   'driving-car',
  camper: 'driving-hgv',
  bike:   'cycling-road',
  walk:   'foot-walking',
  boat:   'driving-car',   // fallback
  mixed:  'driving-car',
}

/**
 * Calculate a real road route between multiple waypoints.
 * Returns { distance_km, duration_min, geometry: [[lng,lat],...] }
 */
export async function calculateRoute(waypoints, tripType = 'car') {
  const apiKey = import.meta.env.VITE_ORS_API_KEY
  if (!apiKey || apiKey === 'YOUR_ORS_KEY') {
    // Fallback: straight lines if no key
    return fallbackRoute(waypoints)
  }

  const profile  = ORS_PROFILE[tripType] || 'driving-car'
  const coords   = waypoints.map(w => [w.lng, w.lat])

  try {
    const res = await fetch(`${ORS_BASE}/directions/${profile}/geojson`, {
      method:  'POST',
      headers: {
        'Authorization': apiKey,
        'Content-Type':  'application/json',
      },
      body: JSON.stringify({ coordinates: coords }),
    })

    if (!res.ok) throw new Error(`ORS ${res.status}`)
    const data = await res.json()
    const feature = data.features[0]
    const summary = feature.properties.summary

    return {
      distance_km:  Math.round(summary.distance / 1000),
      duration_min: Math.round(summary.duration / 60),
      geometry:     feature.geometry.coordinates, // [[lng,lat],...]
      segments:     feature.properties.segments || [],
    }
  } catch (err) {
    console.warn('ORS routing failed, using fallback:', err.message)
    return fallbackRoute(waypoints)
  }
}

/** Straight-line fallback when ORS is unavailable */
function fallbackRoute(waypoints) {
  const geometry = []
  for (let i = 0; i < waypoints.length - 1; i++) {
    const from = waypoints[i]
    const to   = waypoints[i + 1]
    // Interpolate 20 points between each pair
    for (let s = 0; s <= 20; s++) {
      geometry.push([
        from.lng + (to.lng - from.lng) * (s / 20),
        from.lat + (to.lat - from.lat) * (s / 20),
      ])
    }
  }
  const distance_km = Math.round(
    waypoints.reduce((acc, wp, i) => {
      if (i === 0) return 0
      return acc + haversine(waypoints[i - 1], wp)
    }, 0)
  )
  return { distance_km, duration_min: Math.round(distance_km * 1.2), geometry }
}

function haversine(a, b) {
  const R = 6371
  const dLat = ((b.lat - a.lat) * Math.PI) / 180
  const dLng = ((b.lng - a.lng) * Math.PI) / 180
  const x = Math.sin(dLat / 2) ** 2 +
    Math.cos((a.lat * Math.PI) / 180) * Math.cos((b.lat * Math.PI) / 180) *
    Math.sin(dLng / 2) ** 2
  return R * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x))
}

/**
 * Generate a GPX file string from route geometry + waypoints
 */
export function buildGPX(tripTitle, waypoints, geometry) {
  const now   = new Date().toISOString()
  const wpts  = waypoints.map(w =>
    `  <wpt lat="${w.lat}" lon="${w.lng}">
    <name>${escXML(w.name)}</name>
    <desc>${w.nights ? `${w.nights} nights` : ''}</desc>
  </wpt>`
  ).join('\n')

  const trkpts = geometry.map(([lng, lat]) =>
    `      <trkpt lat="${lat}" lon="${lng}"></trkpt>`
  ).join('\n')

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Road-Trip App" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${escXML(tripTitle)}</name>
    <time>${now}</time>
    <desc>Generated by Road-Trip — road-trip.app</desc>
  </metadata>
${wpts}
  <trk>
    <name>${escXML(tripTitle)}</name>
    <trkseg>
${trkpts}
    </trkseg>
  </trk>
</gpx>`
}

function escXML(s) {
  return String(s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')
}

/**
 * Download a GPX file in the browser
 */
export function downloadGPX(filename, gpxString) {
  const blob = new Blob([gpxString], { type: 'application/gpx+xml' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename.replace(/[^a-z0-9]/gi, '_') + '.gpx'
  a.click()
  URL.revokeObjectURL(url)
}
